## LOCAL = http://localhost:8080


@baseUrl = http://localhost:8080

###

## GET Ping Database
GET {{baseUrl}}/ping HTTP/1.1

###

## POST text
POST {{baseUrl}} HTTP/1.1
content-type: text/plain

www.example2.com

###

# @name shortenAPI
## POST SHORTEN
POST {{baseUrl}}/api/shorten HTTP/1.1
content-type: application/json

{
    "url": "http://httpbin.org/delay/2"
}
###

@shortID = {{ shortenAPI.response.body.result }}

## GET ORIGINAL URL
GET {{ shortID }} HTTP/1.1
###

# @name shortenAPIBatch
## POST SHORTEN Batch
POST {{baseUrl}}/api/shorten/batch HTTP/1.1
content-type: application/json

[
    {
        "correlation_id": "100FED",
        "original_url": "http://httpbin.org/delay/3"
    },
    {
        "correlation_id": "200DHF",
        "original_url": "http://httpbin.org/delay/4"
    }
]

###

## DELETE Batch
POST {{baseUrl}}/api/user/urls HTTP/1.1
content-type: application/json

[
    "022cedd1184bff82",
    "b4e8c5d3184bff82",
    "259950ad184bff8a",
    "19ac67f1184bff8a",
    "c3521caf184bff8f"
]

###
