## LOCAL = http://localhost:8080


@baseUrl = http://localhost:8080

###


## POST text
POST {{baseUrl}} HTTP/1.1
content-type: text/plain

 "www.example2.com"

###

# @name shortenAPI
## POST SHORTEN
POST {{baseUrl}}/api/shorten HTTP/1.1
content-type: application/json

{
    "url": "http://httpbin.org/delay/2"
}
###

@shortID = {{ shortenAPI.response.body.result }}

## GET ORIGINAL URL
GET {{ shortID }} HTTP/1.1
###

